"""adding date completed

Revision ID: 4af9cb58f775
Revises: 16c2a8de370c
Create Date: 2024-12-13 16:06:07.947263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af9cb58f775'
down_revision: Union[str, None] = '16c2a8de370c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('date_completed', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'date_completed')
    # ### end Alembic commands ###
