"""Adding json column to ai prompt

Revision ID: ea41c71fd6b6
Revises: fe4bb33b0cea
Create Date: 2024-12-27 10:12:41.980952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea41c71fd6b6'
down_revision: Union[str, None] = 'fe4bb33b0cea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_prompts', sa.Column('returns_json', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_prompts', 'returns_json')
    # ### end Alembic commands ###
